services:

  mysql:
    image: mysql:8.4
    container_name: taskmanager-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped

  task-api:
    build: .

    container_name: taskmanager-api

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_KEY: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=America/Sao_Paulo
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8080:8080"

    restart: unless-stopped

volumes:
  mysql_data: