    #Spring config properties
    spring.config.import=optional:file:.env[.properties]

    #MySQL Database configuration
    spring.datasource.url=${DB_KEY}
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}

    #JPA/Hibernate Configuration
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=true
    spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
    spring.jpa.open-in-view=false

    #JWT
    jwt.security.token.secret-key=${JWT_SECRET}
    jwt.security.token.expiration=${JWT_EXPIRATION}

    #Flyway configuration
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration